spring.application.name=paymentService
server.port=9000

# razorpay setup
razorpay.key_id=rzp_test_RCgIisrOC2BWbt
razorpay.key_secret=zRdyCfcV3YR3gal5KYVVFwB4


# redis setup
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=helloworld!

#postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/QuickDrop
spring.datasource.username=postgres
spring.datasource.password=helloworld!

#mongodb
spring.data.mongodb.uri=mongodb://localhost:27017/payment_data
spring.data.mongodb.database=payment_data
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#kafka properties
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#kafka consumer
#KafkaConfig consumer
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id="order-consume"
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
