spring.application.name=Product
# Database connection settings
server.port=9091
spring.datasource.url=jdbc:postgresql://localhost:5432/QuickDrop
spring.datasource.username=postgres
spring.datasource.password=helloworld!

aws.s3.bucket=quickdrop-images-bucket
cdn.url=https://d1gc8ox052hn8l.cloudfront.net
aws.region=ap-south-1
# JPA settings (optional but useful)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE



# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=helloworld!


#kafka properties
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

#kafka consumer
#KafkaConfig consumer
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id="order-consume"
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

#razorpay config
razorpay.key_id=rzp_test_RCgIisrOC2BWbt
razorpay.key_secret=zRdyCfcV3YR3gal5KYVVFwB4

# mongodb
spring.data.mongodb.uri=mongodb://localhost:27017/user_product_visit
spring.data.mongodb.database=user_product_visit
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

