spring.application.name=User
# Database connection settings
server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/QuickDrop
spring.datasource.username=postgres
spring.datasource.password=helloworld!

spring.security.debug=true

# ? Enable DEBUG logs for authentication and authorization
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
logging.level.org.springframework.security.authorization=DEBUG

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ? Enable DEBUG for JWT parsing (jjwt library)
logging.level.io.jsonwebtoken=DEBUG

# JPA settings (optional but useful)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379
spring.redis.password=helloworld!
# Common Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Consumer
spring.kafka.consumer.group-id=order-consume
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer



#mongoDb setup
spring.data.mongodb.uri=mongodb://localhost:27017/user_product_visit
spring.data.mongodb.database=user_product_visit
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
